package com.laborguru.exception;

/**
 * Error Enum
 * List of SPM errors. All the exceptions thrown by SPM should have an error code here.
 * @author <a href="cnunezre@gmail.com">Cristian Nunez Rebolledo</a>
 * @version 1.0
 * @since SPM 1.0
 *
 */
public enum ErrorEnum {
	GENERIC_ERROR,
	GENERIC_DATABASE_ERROR,
	USERNAME_ALREADY_EXIST_ERROR,
	OPERATION_TIME_IS_NOT_SET_FOR_STORE,
	INVALID_OPERATION_TIME_FOR_STORE,
	PROJECTION_DOES_NOT_EXIST,
	CHANGES_BIGGER_THAN_PROJECTION,
	NO_PROJECTION_VALUES_FOR_SELECTED_WEEKS,
	INVALID_UPLOAD_FILE,
	PARSING_FILE_ERROR,
	REQUIRED_FIELD_IN_FILE_TO_UPLOAD,
	INVALID_FIELD_IN_FILE_TO_UPLOAD,
	FIELD_DOES_NOT_EXIST,
	USERNAME_NOT_EXIST_ERROR,
	STORE_INVALID_ROW,
	INVALID_SECTION_ROW, 
	INVALID_UPLOAD_STORE_ALREADY_EXISTS,
	NO_STORE_IN_SESSION,
	NOT_IMPLEMENTED_METHOD,
	DUPLICATED_POSITION,
	DUPLICATED_POSITION_GROUP,
	STORE_DOES_NOT_EXIST, 
	STORE_NOT_STATIC,
	EMPLOYEE_INVALID_ROW,
	EMPLOYEE_INVALID_CUSTOMER,
	EMPLOYEE_CUSTOMER_REQUIRED,
	EMPLOYEE_STORE_REQUIRED,
	EMPLOYEE_INVALID_DEFAULT_POSITION,
	EMPLOYEE_INVALID_STORE;
}
